SRC_DIR = src/
RENDER_SRCS_DIR = $(SRC_DIR)render/
PARSING_SRCS_DIR = $(SRC_DIR)parser/

MAIN_FILES = main.c

RENDER_FILES = render.c
PARSING_FILES = 

RENDER_SOURCES = $(addprefix $(RENDER_SRCS_DIR), $(RENDER_FILES))
PARSING_SOURCES = $(addprefix $(PARSING_SRCS_DIR), $(PARSING_FILES))

SOURCES = $(MAIN_SOURCES) $(RENDER_SOURCES) $(PARSING_SOURCES)
